export default {
  JOB_CATEGORY: 'JOB_CATEGORY',
  JOB_DETAILS: 'JOB_DETAILS',
  MATERIAL_LIST: 'MATERIAL_LIST',
  PROPERTY_LIST: 'PROPERTY_LIST',
  DATE: 'DATE',
  LOCATION: 'LOCATION',
  WIRING:"WIRING"
};
